INSERT INTO `obrand_db`.`node_tree` (`level`, `iLeft`, `iRight`) VALUES ('2', '2', '3');
SELECT LAST_INSERT_ID();
SELECT `idNode`, `level`, `iLeft`, `iRight` FROM `obrand_db`.`node_tree` WHERE  `idNode`=1;
INSERT INTO `obrand_db`.`node_tree` (`level`, `iLeft`, `iRight`) VALUES ('2', '4', '5');
SELECT LAST_INSERT_ID();
SELECT `idNode`, `level`, `iLeft`, `iRight` FROM `obrand_db`.`node_tree` WHERE  `idNode`=2;
INSERT INTO `obrand_db`.`node_tree` (`level`, `iLeft`, `iRight`) VALUES ('2', '6', '7');
SELECT LAST_INSERT_ID();
SELECT `idNode`, `level`, `iLeft`, `iRight` FROM `obrand_db`.`node_tree` WHERE  `idNode`=3;
INSERT INTO `obrand_db`.`node_tree` (`level`, `iLeft`, `iRight`) VALUES ('2', '8', '9');
SELECT LAST_INSERT_ID();
SELECT `idNode`, `level`, `iLeft`, `iRight` FROM `obrand_db`.`node_tree` WHERE  `idNode`=4;
INSERT INTO `obrand_db`.`node_tree` (`level`, `iLeft`, `iRight`) VALUES ('1', '1', '24');
SELECT LAST_INSERT_ID();
SELECT `idNode`, `level`, `iLeft`, `iRight` FROM `obrand_db`.`node_tree` WHERE  `idNode`=5;
INSERT INTO `obrand_db`.`node_tree` (`level`, `iLeft`, `iRight`) VALUES ('2', '10', '11');
SELECT LAST_INSERT_ID();
SELECT `idNode`, `level`, `iLeft`, `iRight` FROM `obrand_db`.`node_tree` WHERE  `idNode`=6;
INSERT INTO `obrand_db`.`node_tree` (`level`, `iLeft`, `iRight`) VALUES ('2', '12', '19');
SELECT LAST_INSERT_ID();
SELECT `idNode`, `level`, `iLeft`, `iRight` FROM `obrand_db`.`node_tree` WHERE  `idNode`=7;
INSERT INTO `obrand_db`.`node_tree` (`level`, `iLeft`, `iRight`) VALUES ('3', '15', '16');
SELECT LAST_INSERT_ID();
SELECT `idNode`, `level`, `iLeft`, `iRight` FROM `obrand_db`.`node_tree` WHERE  `idNode`=8;
INSERT INTO `obrand_db`.`node_tree` (`level`, `iLeft`, `iRight`) VALUES ('3', '17', '18');
SELECT LAST_INSERT_ID();
SELECT `idNode`, `level`, `iLeft`, `iRight` FROM `obrand_db`.`node_tree` WHERE  `idNode`=9;
INSERT INTO `obrand_db`.`node_tree` (`level`, `iLeft`, `iRight`) VALUES ('2', '20', '21');
SELECT LAST_INSERT_ID();
SELECT `idNode`, `level`, `iLeft`, `iRight` FROM `obrand_db`.`node_tree` WHERE  `idNode`=10;
INSERT INTO `obrand_db`.`node_tree` (`level`, `iLeft`, `iRight`) VALUES ('3', '13', '14');
SELECT LAST_INSERT_ID();
SELECT `idNode`, `level`, `iLeft`, `iRight` FROM `obrand_db`.`node_tree` WHERE  `idNode`=11;
INSERT INTO `obrand_db`.`node_tree` (`level`, `iLeft`, `iRight`) VALUES ('2', '22', '23');
SELECT LAST_INSERT_ID();
SELECT `idNode`, `level`, `iLeft`, `iRight` FROM `obrand_db`.`node_tree` WHERE  `idNode`=12;


INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('1', 'english', 'Marketing');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('1', 'italian', 'Marketing');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('2', 'english', 'Helpdesk');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('2', 'italian', 'Supporto Tecnico');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('3', 'english', 'Managers');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('3', 'italian', 'Manager');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('4', 'english', 'Customer Account');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('4', 'italian', 'Assistenza Clienti');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('5', 'english', 'Obrand Srl');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('5', 'italian', 'Obrand Srl');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('6', 'english', 'Accounting');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('6', 'italian', 'Amministrazione');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('7', 'english', 'Sales');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('7', 'italian', 'Supporto Vendite');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('8', 'english', 'Italy');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('8', 'italian', 'Italia');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('9', 'english', 'Europe');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('9', 'italian', 'Europa');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('10', 'english', 'Developers');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('10', 'italian', 'Sviluppatori');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('11', 'english', 'North America');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('11', 'italian', 'Nord America');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('12', 'english', 'Quality Assurance');
INSERT INTO `obrand_db`.`node_tree_names` (`idNode`, `language`, `NodeName`) VALUES ('12', 'italian', 'Controllo Qualità');